//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challengers.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challengers.Shared.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player cannot participate more than once in a tournament..
        /// </summary>
        internal static string DuplicatedPlayerInTournament {
            get {
                return ResourceManager.GetString("DuplicatedPlayerInTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} * {1} (skill) + {2} * {3} (reaction time) + {4} * {5} (luck) = {6} total score.
        /// </summary>
        internal static string FemaleScoreExplanation {
            get {
                return ResourceManager.GetString("FemaleScoreExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Format error in message: {0}.
        /// </summary>
        internal static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        internal static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid gender. Must be &apos;{0}&apos; or &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid player data..
        /// </summary>
        internal static string InvalidPlayerData {
            get {
                return ResourceManager.GetString("InvalidPlayerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} * {1} (skill) + {2} * {3} (strength) + {4} * {5} (speed) + {6} * {7} (luck) = {8} total score.
        /// </summary>
        internal static string MaleScoreExplanation {
            get {
                return ResourceManager.GetString("MaleScoreExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match has already been simulated..
        /// </summary>
        internal static string MatchAlreadySimulated {
            get {
                return ResourceManager.GetString("MatchAlreadySimulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both players must be provided to simulate a match..
        /// </summary>
        internal static string MatchPlayersRequired {
            get {
                return ResourceManager.GetString("MatchPlayersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player cannot play against themselves..
        /// </summary>
        internal static string MatchSamePlayer {
            get {
                return ResourceManager.GetString("MatchSamePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player cannot have both reaction time and strength/speed..
        /// </summary>
        internal static string MixedGenderAttributes {
            get {
                return ResourceManager.GetString("MixedGenderAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name must be at most {0} characters..
        /// </summary>
        internal static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found..
        /// </summary>
        internal static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player with ID {0} not found..
        /// </summary>
        internal static string PlayerIdNotFound {
            get {
                return ResourceManager.GetString("PlayerIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player ID is required when referencing an existing player..
        /// </summary>
        internal static string PlayerIdRequired {
            get {
                return ResourceManager.GetString("PlayerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Player ID or full player data required..
        /// </summary>
        internal static string PlayerReferenceInvalid {
            get {
                return ResourceManager.GetString("PlayerReferenceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction time must be between {0} and {1}..
        /// </summary>
        internal static string ReactionOutOfRange {
            get {
                return ResourceManager.GetString("ReactionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction time is not allowed for male players..
        /// </summary>
        internal static string ReactionTimeNotAllowedForMale {
            get {
                return ResourceManager.GetString("ReactionTimeNotAllowedForMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction time is required for female players..
        /// </summary>
        internal static string ReactionTimeRequired {
            get {
                return ResourceManager.GetString("ReactionTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill must be between {0} and {1}..
        /// </summary>
        internal static string SkillOutOfRange {
            get {
                return ResourceManager.GetString("SkillOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill is required for new players..
        /// </summary>
        internal static string SkillRequired {
            get {
                return ResourceManager.GetString("SkillRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female players must not have speed..
        /// </summary>
        internal static string SpeedNotAllowedForFemale {
            get {
                return ResourceManager.GetString("SpeedNotAllowedForFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed must be between {0} and {1}..
        /// </summary>
        internal static string SpeedOutOfRange {
            get {
                return ResourceManager.GetString("SpeedOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed is required for male players..
        /// </summary>
        internal static string SpeedRequiredForMale {
            get {
                return ResourceManager.GetString("SpeedRequiredForMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female players must not have strength..
        /// </summary>
        internal static string StrengthNotAllowedForFemale {
            get {
                return ResourceManager.GetString("StrengthNotAllowedForFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength must be between {0} and {1}..
        /// </summary>
        internal static string StrengthOutOfRange {
            get {
                return ResourceManager.GetString("StrengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength is required for male players..
        /// </summary>
        internal static string StrengthRequiredForMale {
            get {
                return ResourceManager.GetString("StrengthRequiredForMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player surname is required..
        /// </summary>
        internal static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player surname must be at most {0} characters..
        /// </summary>
        internal static string SurnameTooLong {
            get {
                return ResourceManager.GetString("SurnameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament has already been completed..
        /// </summary>
        internal static string TournamentAlreadyCompleted {
            get {
                return ResourceManager.GetString("TournamentAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tournament named &apos;{0}&apos; already exists..
        /// </summary>
        internal static string TournamentAlreadyExists {
            get {
                return ResourceManager.GetString("TournamentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament created successfully..
        /// </summary>
        internal static string TournamentCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TournamentCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament gender is required..
        /// </summary>
        internal static string TournamentGenderRequired {
            get {
                return ResourceManager.GetString("TournamentGenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of players must be a power of two and non-zero..
        /// </summary>
        internal static string TournamentInvalidPlayerCount {
            get {
                return ResourceManager.GetString("TournamentInvalidPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament name is required..
        /// </summary>
        internal static string TournamentNameRequired {
            get {
                return ResourceManager.GetString("TournamentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament name must be at most {0} characters..
        /// </summary>
        internal static string TournamentNameTooLong {
            get {
                return ResourceManager.GetString("TournamentNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament with ID {0} not found..
        /// </summary>
        internal static string TournamentNotFound {
            get {
                return ResourceManager.GetString("TournamentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players list cannot be empty..
        /// </summary>
        internal static string TournamentPlayersEmpty {
            get {
                return ResourceManager.GetString("TournamentPlayersEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following players do not match the tournament gender &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string TournamentPlayersGenderMismatch {
            get {
                return ResourceManager.GetString("TournamentPlayersGenderMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed..
        /// </summary>
        internal static string ValidationFailedMessage {
            get {
                return ResourceManager.GetString("ValidationFailedMessage", resourceCulture);
            }
        }
    }
}
