//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challengers.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challengers.Shared.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} * {1} (skill) + {2} * {3} (reaction time) + {4} * {5} (luck) = {6} total score.
        /// </summary>
        internal static string FemaleScoreExplanation {
            get {
                return ResourceManager.GetString("FemaleScoreExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Format error in message: {0}.
        /// </summary>
        internal static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Invalid gender. Must be &apos;{0}&apos; or &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} * {1} (skill) + {2} * {3} (strength) + {4} * {5} (speed) + {6} * {7} (luck) = {8} total score.
        /// </summary>
        internal static string MaleScoreExplanation {
            get {
                return ResourceManager.GetString("MaleScoreExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match has already been simulated..
        /// </summary>
        internal static string MatchAlreadySimulated {
            get {
                return ResourceManager.GetString("MatchAlreadySimulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both players must be provided to simulate a match..
        /// </summary>
        internal static string MatchPlayersRequired {
            get {
                return ResourceManager.GetString("MatchPlayersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player cannot play against themselves..
        /// </summary>
        internal static string MatchSamePlayer {
            get {
                return ResourceManager.GetString("MatchSamePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction time must be between {0} and {1}..
        /// </summary>
        internal static string ReactionOutOfRange {
            get {
                return ResourceManager.GetString("ReactionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill must be between {0} and {1}..
        /// </summary>
        internal static string SkillOutOfRange {
            get {
                return ResourceManager.GetString("SkillOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed must be between {0} and {1}..
        /// </summary>
        internal static string SpeedOutOfRange {
            get {
                return ResourceManager.GetString("SpeedOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength must be between {0} and {1}..
        /// </summary>
        internal static string StrengthOutOfRange {
            get {
                return ResourceManager.GetString("StrengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The tournament has already been completed..
        /// </summary>
        internal static string TournamentAlreadyCompleted {
            get {
                return ResourceManager.GetString("TournamentAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament created successfully..
        /// </summary>
        internal static string TournamentCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TournamentCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of players must be a power of two and non-zero..
        /// </summary>
        internal static string TournamentInvalidPlayerCount {
            get {
                return ResourceManager.GetString("TournamentInvalidPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tournament name is required..
        /// </summary>
        internal static string TournamentNameRequired {
            get {
                return ResourceManager.GetString("TournamentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament not found..
        /// </summary>
        internal static string TournamentNotFound {
            get {
                return ResourceManager.GetString("TournamentNotFound", resourceCulture);
            }
        }
    }
}
