name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: simonholmquist/challengers-api:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          file: ./src/Challengers.Api/Dockerfile.azure
          push: true
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}
          tags: |
            simonholmquist/challengers-api:latest
            simonholmquist/challengers-api:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger Azure Web App Deployment
        run: |
          curl -X POST "${{ secrets.AZURE_WEBHOOK_URL }}"
